rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
notifications:
  recipients:
    - memde@engineyard.com
  webhooks:
    urls:
      - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true
